### PR TITLE
Fix for Issue #93: Collection associations can be overwritten if made while release branch is opened

### PR DESCRIPTION
**Pull request by Phoeneix**
Github Issue: #93

### Overview of work done

Removed code from build pipeline that causes this issue.

### Overview of verification done

Executed build

## PR checklist:

* [ ] Linted
* [ ] Updated unit tests
* [x] Updated changelog
* [ ] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Review by skorper — COMMENTED** [review]
I don't think we want to remove the cmr-umm-updater call entirely.. that would mean our umm-s entry was never updated with the latest version

**Comment by Phoeneix** [comment]
@skorper 
I removed that step, because it's only executed when the PR name contains "release" and targeting the main branch. It updates the cmr association with the local data, which was the cause of the related issue.
If you think it should not be removed, I do not see any way to fix the related issue where an update on release happens and overwrites the data.
If we expect that update on release, then the related issue is not an issue anymore but an expected behavior.

**Comment by frankinspace** [comment]
We need to be able to do both. We need to be able to update the umm-s record in UAT when there is a release branch open and we also need to be able to update cmr association data. What we want to avoid is if a new association happens while a release is open, merging the release should not discard that new association that was made.

Probably the easiest fix is a process change where the individual managing the release checks and makes sure no new associations were added during the time the release was open and if there were, to pull those in to the release before merging to master.

**Comment by Phoeneix** [comment]
@frankinspace  If you can point out what counts as a newer association (higher version or other factors too?), then I can make changes to the updater to ignore those situations

**Pull request closed without merging**
