### PR TITLE
Feature/issue-205

### PR DESCRIPTION
**Pull request by nlenssen2013**
Github Issue: #205 , #220

### Description

If there are dimensions that have the same string name but different values in different groups. Then the xarray.rename_dims function will need to be used so that the copying variables back into the netCDF dataset is successfull

### Overview of work done

get the names of dimensions that have different values and then put the old name and new name into the .rename_dims for an updated dataset. Check that the same time variable isn't added

### Overview of verification done

run bounding box test on OMIPIXCOR data file

### Overview of integration done

_Explain how this change was integration tested. Provide screenshots or logs if appropriate. An example of this would be a local Harmony deployment._

## PR checklist:

* [x] Linted
* [x] Updated unit tests
* [x] Updated changelog
* [ ] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Comment by nlenssen2013** [comment]
Synk seems to be failing, and I'm not sure how to trouble shoot that

**Comment by jamesfwood** [comment]
@nlenssen2013 there are some conflicts that need fixing.  Also, don't worry about the Synk and SonarCloud failure.  I have another branch to address that.  But if you can fix the conflicts then we should be able to merge this.

**Comment by nlenssen2013** [comment]
> @nlenssen2013 there are some conflicts that need fixing. Also, don't worry about the Synk and SonarCloud failure. I have another branch to address that. But if you can fix the conflicts then we should be able to merge this.

Conflicts are fixed. Added a small issue fix with the compute time coordinates function. Let me know if it's acceptable.

**Review by jamesfwood — APPROVED** [review]
Looks good, merge when you're ready.  Thanks!

**Pull request merged**
