### PR TITLE
update ascending flag variable clean up

### PR DESCRIPTION
**Pull request by nlenssen2013**
Github Issue: #153 

### Description

xarray decode times chokes on blank ascending time variable

### Overview of work done

remove the variable if the flag indicates it is blank

### Overview of verification done

Open up three different files, ascending, descending and both

### Overview of integration done

_Explain how this change was integration tested. Provide screenshots or logs if appropriate. An example of this would be a local Harmony deployment._

## PR checklist:

* [x] Linted
* [x] Updated unit tests
* [x] Updated changelog
* [ ] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Review by jamesfwood — COMMENTED** [review]
Looks good Nick.  Could you do me a favor though?  Could you roll those dependabot updates into this PR?  Bump werkzeug to 2.2.3, and cryptography to 39.0.1.
It may need a poetry update, but not sure.  Thanks!

**Comment by jamesfwood** [comment]
> > Looks good Nick. Could you do me a favor though? Could you roll those dependabot updates into this PR? Bump werkzeug to 2.2.3, and cryptography to 39.0.1. It may need a poetry update, but not sure. Thanks!
> 
> > Looks good Nick. Could you do me a favor though? Could you roll those dependabot updates into this PR? Bump werkzeug to 2.2.3, and cryptography to 39.0.1. It may need a poetry update, but not sure. Thanks!
> 
> Got it, so merge the other two pull requests into this one?

Yeah, or just update those versions and after it passes I can just close those tickets.  Either way, up to you.

**Comment by nlenssen2013** [comment]
> > > Looks good Nick. Could you do me a favor though? Could you roll those dependabot updates into this PR? Bump werkzeug to 2.2.3, and cryptography to 39.0.1. It may need a poetry update, but not sure. Thanks!
> > 
> > 
> > > Looks good Nick. Could you do me a favor though? Could you roll those dependabot updates into this PR? Bump werkzeug to 2.2.3, and cryptography to 39.0.1. It may need a poetry update, but not sure. Thanks!
> > 
> > 
> > Got it, so merge the other two pull requests into this one?
> 
> Yeah, or just update those versions and after it passes I can just close those tickets. Either way, up to you.

Okay, so I did poetry add werkzeug=='2.2.3' and poetry add cryptography=='39.0.1'. Then did a poetry update, pushed the changes in the lock and toml files. Seems like I poetry version is still wrong....

**Comment by frankinspace** [comment]
@nlenssen2013 you just need to run `poetry update` and then check in the new poetry.lock file that gets generated. I ran it and the updated version are there now.

**Review by frankinspace — APPROVED** [review]

**Comment by nlenssen2013** [comment]
> @nlenssen2013 you just need to run `poetry update` and then check in the new poetry.lock file that gets generated. I ran it and the updated version are there now.

Looks like it's still failing at the same spot

**Comment by frankinspace** [comment]
Didn't realize the action was also failing, that was a separate problem. Needed to bump the version of poetry the github action itself was using.

**Comment by nlenssen2013** [comment]
> Didn't realize the action was also failing, that was a separate problem. Needed to bump the version of poetry the github action itself was using.

You alright if I merge this?

**Comment by frankinspace** [comment]
Need to figure out why tests are failing

**Comment by nlenssen2013** [comment]
> Need to figure out why tests are failing

Will this get figured out this week?

**Comment by jamesfwood** [comment]
@nlenssen2013 Would you have time to fix the tests or if not I can do it.  Let me know, thanks!

**Comment by nlenssen2013** [comment]
> @nlenssen2013 Would you have time to fix the tests or if not I can do it. Let me know, thanks!

I can work on it today, but tests are passing when I run it locally. I have the updated cryptography and werkzeug versions as well - so not sure where to trouble shoot

**Comment by jamesfwood** [comment]
> > @nlenssen2013 Would you have time to fix the tests or if not I can do it. Let me know, thanks!
> 
> I can work on it today, but tests are passing when I run it locally. I have the updated cryptography and werkzeug versions as well - so not sure where to trouble shoot

Ok, that would be great.  Did you see the error in Github Actions?  It's something with this:
AttributeError: module 'numpy' has no attribute 'warnings'

Maybe your local version has a different version of numpy?

Thanks for checking it out!
Also, sorry about the trouble with updating those two libraries.  Didn't think it would cause so many problems.

**Comment by nlenssen2013** [comment]
> > > @nlenssen2013 Would you have time to fix the tests or if not I can do it. Let me know, thanks!
> > 
> > 
> > I can work on it today, but tests are passing when I run it locally. I have the updated cryptography and werkzeug versions as well - so not sure where to trouble shoot
> 
> Ok, that would be great. Did you see the error in Github Actions? It's something with this: AttributeError: module 'numpy' has no attribute 'warnings'
> 
> Maybe your local version has a different version of numpy?
> 
> Thanks for checking it out! Also, sorry about the trouble with updating those two libraries. Didn't think it would cause so many problems.

Does numpy need to be 1.24? because everything goes through and passes when it remains numpy==1.23.5

**Comment by jamesfwood** [comment]
> > > > @nlenssen2013 Would you have time to fix the tests or if not I can do it. Let me know, thanks!
> > > 
> > > 
> > > I can work on it today, but tests are passing when I run it locally. I have the updated cryptography and werkzeug versions as well - so not sure where to trouble shoot
> > 
> > 
> > Ok, that would be great. Did you see the error in Github Actions? It's something with this: AttributeError: module 'numpy' has no attribute 'warnings'
> > Maybe your local version has a different version of numpy?
> > Thanks for checking it out! Also, sorry about the trouble with updating those two libraries. Didn't think it would cause so many problems.
> 
> Does numpy need to be 1.24? because everything goes through and passes when it remains numpy==1.23.5

yeah go ahead and downgrade numpy to 1.23.5 and push it and see if that works in github actions.

**Comment by nlenssen2013** [comment]
> > > > > > @nlenssen2013 Would you have time to fix the tests or if not I can do it. Let me know, thanks!
> > > > > 
> > > > > 
> > > > > I can work on it today, but tests are passing when I run it locally. I have the updated cryptography and werkzeug versions as well - so not sure where to trouble shoot
> > > > 
> > > > 
> > > > Ok, that would be great. Did you see the error in Github Actions? It's something with this: AttributeError: module 'numpy' has no attribute 'warnings'
> > > > Maybe your local version has a different version of numpy?
> > > > Thanks for checking it out! Also, sorry about the trouble with updating those two libraries. Didn't think it would cause so many problems.
> > > 
> > > 
> > > Does numpy need to be 1.24? because everything goes through and passes when it remains numpy==1.23.5
> > 
> > 
> > yeah go ahead and downgrade numpy to 1.23.5 and push it and see if that works in github actions.

Was just trying to delete my comment - looks like sonar cloud isn't too happy

**Review by jamesfwood — APPROVED** [review]

**Pull request merged**
