### PR TITLE
change conditional array slice from 1st index to most True values

### PR DESCRIPTION
**Pull request by danielfromearth**
Github Issue: #226 

### Description

This changes the trimming of the conditional array when subsetting _both_ spatially and temporally, so that valid values in the time variable (for TEMPO data) are not inadvertently lost.

### Overview of work done

The logic has been changed.  Before, the first index of the missing dimension was selected naively. Now, the conditional array is iterated over to find the row/column that has the most True values and that row/column is selected.

### Overview of verification done

Tested this manually with TEMPO data locally. Ran and passed all of the automated tests for the subset module.

### Overview of integration done

None.

## PR checklist:

* [x] Linted
* [ ] Updated unit tests
* [x] Updated changelog
* [ ] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Comment by danielfromearth** [comment]
Hi @jamesfwood, looks like there is an issue with dependency versions that Snyk wants addressed. Can you help with addressing this?

**Comment by jamesfwood** [comment]
> Hi @jamesfwood, looks like there is an issue with dependency versions that Snyk wants addressed. Can you help with addressing this?



> Hi @jamesfwood, looks like there is an issue with dependency versions that Snyk wants addressed. Can you help with addressing this?

Hi @danielfromearth, if you pull in the latest develop into your branch it and repush should fix the issue.  It updated pillow version.

**Review by jamesfwood — APPROVED** [review]

**Comment by danielfromearth** [comment]
Status update: one of the automated tests (`tests/test_subset.py::test_cf_decode_times_sndr`) just started failing after updating the poetry dependencies. It appears to be failing on an xarray `.where()` function for a single variable (`/local_solar_time`) in the SNDR data.

**Comment by danielfromearth** [comment]
Update: 
Well, this fix to extend the `xarray.open_dataset()`'s `mask_and_scale` application to more time variables seems to have worked, as it replaces null values with fill values to avoid the Overflow error.  So, perhaps we can ignore the null time values in this test data file for now.  The SNDR team may still want to confirm whether those null values in the `local_solar_time` array are expected.

**Review by sliu008 — APPROVED** [review]

**Comment by danielfromearth** [comment]
Thanks @sliu008 for reviewing this too!

**Pull request merged**
